PHRASES = [
        ("Houston Strong", "A motto from the 4th largest city in the US"),
        ("Just do it", "Shoe slogan"),
        ("The bright side", "The side of life that you should always look on"),
        ("May the force be with you", "What is always with you in this space series"),
        ("The rug", "Item that really ties the room together man"),
        ("I am iron man", "Song line that a marvel character might sing"),
        ("To be or not to be", "Shakespearian Question"),
        ("Adapt and overcome", "United States Marine Corps saying"),
        ("We are the knights that say nee", "The kind of knights we are"),
        ("Spam and eggs", "Python meal"),
        ("We aim to misbehave", "Browncoasts motto in Firefly"),
        ("Tim", "The Enchanter"),
        ("Coconuts", "Makes horse sounds in Monty Python"),
        ("The Romans", "What have they ever done for us?"),
        ("Holy handgrenade", "Item that you should count to three before throwing"),
        ("Lumberjack", "Sleeps all night, works all day"),
        ("The Last Crusade", "The best Indiana Jones movie"),
        ("The Dude", "Doesn't like to be called Mr. Lebowski"),
    ]